### ISSUE TITLE
ln: failed to create symbolic link 

### ISSUE THREAD

**Issue by Pepsi-Guy** [Mr-Robert0/Logsensor#2]
Hello !
I have this problem
./install.sh
ln: failed to create symbolic link '/usr/local/bin/logsensor': File exists

**Comment by Mr-Robert0** [comment]
This mean that is sym link for logsensor is already created , 
so You can run it simply

nevertheless , you can delete sym link : 
sudo rm /usr/local/bin/logsensor

Then run ./install.sh again

**Comment by tamimhasan404** [comment]
Yeah. It shows when you do ./install.sh but if you run this tool normally it's works fine.

**Comment by Mr-Robert0** [comment]
Because this script ./install creates a sym link, so it is Expected error message if you run ./install again it tells you that is sym link it already exists and failed to create symbolic link '
